name: "pull request, review on chatGPT"

on:
  push:
    branches:
      - master
      - review
    paths:
      - *.yaml
      - *.yml

permissions:
  id-token: write
  contents: read

jobs:
  review:
    name: Source Review by ChatGpt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source.
        uses: actions/checkout@v4
      - name: Review on chatGPT 
        uses: anc95/ChatGPT-CodeReview@main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
  